# -*- coding: utf-8 -*-
"""spam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYz4n8R9SlZYH3VLhmzPmOMdGLgCL0QN
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from google.colab import files
import io

uploaded = files.upload()

dataset_path = next(iter(uploaded.keys()))

df = pd.read_csv(io.StringIO(uploaded[dataset_path].decode('utf-8')))

print(df.head())

print(df.columns)

X_train, X_test, y_train, y_test = train_test_split(df['Category'], df['Message'], test_size=0.2, random_state=42)

vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = LogisticRegression()
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')